import os
import sys
import types
from datetime import datetime
from unittest.mock import MagicMock

import pytest
import pytest_asyncio  # <--- 新增导入
from sqlalchemy import String
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import Mapped, mapped_column

# ==========================================
# 1. 混合 Mock 策略 (保持不变，这部分是正确的)
# ==========================================

current_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.dirname(os.path.dirname(current_dir))
pkg_path = os.path.join(project_root, "pkg")

# 添加项目根目录到 sys.path
if project_root not in sys.path:
    sys.path.insert(0, project_root)

mock_pkg = types.ModuleType("pkg")
mock_pkg.__path__ = [pkg_path]

mock_pkg.orjson_dumps = lambda x: "json"
mock_pkg.orjson_loads = lambda x: {}
mock_pkg.orjson_loads_types = (str, bytes)
mock_pkg.utc_now_naive = lambda: datetime.utcnow()
mock_pkg.unique_list = lambda x, exclude_none=False: list(
    set([i for i in x if i is not None] if exclude_none else x)
)

# Mock context module
mock_context = types.ModuleType("pkg.request_context")
mock_context.get_user_id = lambda: 999

mock_logger = MagicMock()

# Mock snowflake ID generator
_id_counter = 0


def mock_gen_id():
    global _id_counter
    _id_counter += 1
    return _id_counter


mock_snowflake_module = types.ModuleType("pkg.ids")
mock_snowflake_generator = types.SimpleNamespace()
mock_snowflake_generator.generate = mock_gen_id
mock_snowflake_module.snowflake_id_generator = mock_snowflake_generator

_patched_module_names = ("pkg.request_context", "pkg.logger_tool", "pkg.ids")
_previous_modules = {name: sys.modules.get(name) for name in _patched_module_names}

# 不要 mock pkg 主模块，让它正常导入
# sys.modules["pkg"] = mock_pkg
sys.modules["pkg.request_context"] = mock_context
sys.modules["pkg.logger_tool"] = mock_logger
sys.modules["pkg.ids"] = mock_snowflake_module

# ==========================================
# 2. 导入目标代码
# ==========================================
try:
    from pkg.database import (
        Base,
        BaseDao,
        AuditActor,
        AuditActorType,
        ModelMixin,
        new_async_session_maker,
    )
    from pkg.database import base as database_base
    from pkg.toolkit.string import escape_like_pattern
except ImportError as e:
    print(f"Import Error: {e}")
    print(f"Looking for pkg at: {pkg_path}")
    raise e
finally:
    for _module_name, _module in _previous_modules.items():
        if _module is None:
            sys.modules.pop(_module_name, None)
        else:
            sys.modules[_module_name] = _module


# ==========================================
# 3. 定义测试模型
# ==========================================
class User(ModelMixin):
    __tablename__ = "users"
    username: Mapped[str] = mapped_column(String(50))
    email: Mapped[str] = mapped_column(String(100), nullable=True)


class Admin(ModelMixin):
    __tablename__ = "admins"
    username: Mapped[str] = mapped_column(String(50))


class UserDao(BaseDao[User]):
    _model_cls: type[User] = User


# ==========================================
# 4. Pytest Fixtures (关键修改区域)
# ==========================================


# 修改点：使用 @pytest_asyncio.fixture 替代 @pytest.fixture
# 并且显式指定 loop_scope="function" 以符合新版规范
@pytest_asyncio.fixture(loop_scope="function")
async def db_session():
    # 使用内存 SQLite
    engine = create_async_engine("sqlite+aiosqlite:///:memory:", echo=False)

    # 建表
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    session_maker = new_async_session_maker(engine)

    yield session_maker

    await engine.dispose()


@pytest.fixture
def _context_user():
    if hasattr(database_base.context, "init"):
        database_base.context.init(user_id=999)
    yield
    if hasattr(database_base.context, "clear"):
        database_base.context.clear()


@pytest.fixture(autouse=True)
def context_user(_context_user):
    return None


@pytest.fixture
def user_dao(db_session):
    # 这里 db_session 是异步 fixture，user_dao 是同步 fixture
    # pytest-asyncio 能够处理这种依赖，只要 db_session 定义正确
    return UserDao(session_provider=db_session)


# ==========================================
# 5. 测试用例
# ==========================================


@pytest.mark.asyncio
async def test_create_and_insert_strictness(user_dao, db_session):
    """测试创建对象、严格Insert检查和ID生成"""
    # 1. Create (Transient)
    user = User.create(username="alice")
    assert user.id is not None, "ID should be generated by create()"
    assert user.creator_id == 999
    assert user.creator_type == AuditActorType.USER.value

    # 2. Insert (严格插入)
    await user_dao.insert(user)

    # 验证数据库
    db_user = await user_dao.query_by_primary_id(user.id)
    assert db_user is not None
    assert db_user.username == "alice"

    # 3. Strict Insert 检查 (持久化对象不能调 insert)
    with pytest.raises(RuntimeError) as exc:
        db_user.prepare_insert_values()
    assert "strictly for INSERT" in str(exc.value)


@pytest.mark.asyncio
async def test_update_strictness(user_dao, db_session):
    """测试更新逻辑和严格Update检查"""
    user = User.create(username="bob")
    await user_dao.insert(user)

    # 1. Update Persistent Object
    db_user = await user_dao.query_by_primary_id(user.id)
    await user_dao.update(db_user, {User.username: "bob_updated"})  # 更新并持久化

    reloaded = await user_dao.query_by_primary_id(user.id)
    assert reloaded.username == "bob_updated"
    assert reloaded.updater_id == 999

    with pytest.raises(ValueError, match="Unknown or managed User update column"):
        db_user.prepare_update(usernmae="typo")
    assert db_user.username == "bob_updated"

    # 2. Strict Update 检查 (新对象不能调 update)
    new_user = User.create(username="charlie")
    with pytest.raises(RuntimeError) as exc:
        new_user.prepare_update(username="fail")
    assert "requires a persisted" in str(exc.value)


@pytest.mark.asyncio
async def test_batch_insert_instances(user_dao, db_session):
    """测试批量对象插入"""
    users = [User.create(username=f"user_{i}") for i in range(5)]

    await user_dao.insert_instances(items=users)

    async with user_dao.session_provider() as session:
        count = (await session.execute(user_dao.count_stmt())).scalar()
    assert count == 5

    ids = [u.id for u in users]
    fetched = await user_dao.query_by_ids(ids)
    assert len(fetched) == 5


@pytest.mark.asyncio
async def test_batch_insert_rows(user_dao, db_session):
    """测试批量字典插入"""
    rows = [{"username": "dict_1"}, {"username": "dict_2"}]

    await user_dao.insert_rows(rows=rows)

    async with user_dao.session_provider() as session:
        count = (await session.execute(user_dao.count_stmt())).scalar()
    assert count == 2


def test_build_batch_insert_statements(user_dao):
    rows_stmt = user_dao.build_insert_rows_stmt(rows=[{"username": "row_user"}])
    assert rows_stmt is not None

    users = [User.create(username="stmt_user")]
    instances_stmt = user_dao.build_insert_instances_stmt(items=users)
    assert instances_stmt is not None
    assert users[0].id is not None


def test_dao_statement_factory_applies_query_policies(user_dao):
    assert "ORDER BY" not in str(user_dao.select_stmt())
    assert "deleted_at IS NULL" in str(user_dao.select_stmt())
    assert "deleted_at IS NULL" not in str(user_dao.select_stmt(include_deleted=True))

    update_statement = user_dao.update_stmt(
        User.id == 1,
        values={"username": "renamed"},
    )
    assert "deleted_at IS NULL" in str(update_statement)
    update_including_deleted = user_dao.update_stmt(
        User.id == 1,
        values={"username": "restored"},
        include_deleted=True,
    )
    assert "deleted_at IS NULL" not in str(update_including_deleted)


def test_update_statement_rejects_unknown_and_managed_columns(user_dao):
    with pytest.raises(ValueError, match="Unknown or managed User update column"):
        user_dao.update_stmt(User.id == 1, values={"usernmae": "alice"})

    with pytest.raises(ValueError, match="Unknown or managed User update column"):
        user_dao.update_stmt(User.id == 1, values={"updater_id": 1})


def test_update_statement_rejects_unscoped_update(user_dao):
    with pytest.raises(ValueError, match="update requires explicit conditions"):
        user_dao.update_stmt(values={"username": "renamed"})


@pytest.mark.asyncio
async def test_query_does_not_commit_read_session(user_dao, monkeypatch):
    user = User.create(username="read_without_commit")
    await user_dao.insert(user)

    async def _unexpected_commit(self):
        raise AssertionError("read query must not commit")

    monkeypatch.setattr(AsyncSession, "commit", _unexpected_commit)

    stored = await user_dao.query_by_primary_id(user.id)

    assert stored is not None


@pytest.mark.asyncio
async def test_instance_model_must_match_dao_model(user_dao):
    admin = Admin.create(username="root")

    with pytest.raises(TypeError) as exc:
        await user_dao.insert(admin)
    assert "expects User" in str(exc.value)

    with pytest.raises(TypeError):
        await user_dao.update(admin, username="root2")

    with pytest.raises(TypeError):
        await user_dao.soft_delete(admin)

    with pytest.raises(TypeError):
        await user_dao.restore(admin)

    with pytest.raises(TypeError):
        user_dao.build_insert_instances_stmt(items=[User.create(username="ok"), admin])


@pytest.mark.asyncio
async def test_select_statement_composes_with_sqlalchemy(user_dao, db_session):
    """测试 DAO statement 可直接使用 SQLAlchemy 组合。"""
    # 准备数据
    await user_dao.insert_rows(rows=[{"username": f"u{i}"} for i in range(1, 6)])

    # Test IN with values
    async with user_dao.read_session_provider() as session:
        result = await session.execute(
            user_dao.select_stmt().where(User.username.in_(["u1", "u2"]))
        )
        res = list(result.scalars().all())
    assert len(res) == 2

    assert await user_dao.query_by_ids([]) == []

    # Test Pagination
    async with user_dao.read_session_provider() as session:
        result = await session.execute(
            user_dao.select_stmt().order_by(User.id.asc()).offset(0).limit(2)
        )
        page_res = list(result.scalars().all())
    assert len(page_res) == 2
    assert page_res[0].username == "u1"


@pytest.mark.asyncio
async def test_like_query_treats_pattern_as_literal_text(user_dao):
    await user_dao.insert_rows(
        rows=[
            {"username": "prefix-100%_done-suffix"},
            {"username": "prefix-100x_done-suffix"},
            {"username": "prefix-100%xdone-suffix"},
        ]
    )

    async with user_dao.read_session_provider() as session:
        escaped_pattern = escape_like_pattern("100%_done")
        query_result = await session.execute(
            user_dao.select_stmt().where(
                User.username.like(f"%{escaped_pattern}%", escape="\\")
            )
        )
        result = list(query_result.scalars().all())

    assert [user.username for user in result] == ["prefix-100%_done-suffix"]


@pytest.mark.asyncio
async def test_soft_delete(user_dao, db_session):
    """测试软删除"""
    user = User.create(username="del_me")
    active_user = User.create(username="keep_me")
    await user_dao.insert(user)
    await user_dao.insert(active_user)

    await user_dao.soft_delete(user)

    async with user_dao.read_session_provider() as session:
        active = (
            (await session.execute(user_dao.select_stmt().where(User.id == user.id)))
            .scalars()
            .first()
        )
        deleted = (
            (
                await session.execute(
                    user_dao.select_stmt(include_deleted=True).where(User.id == user.id)
                )
            )
            .scalars()
            .first()
        )
        deleted_by_filter = (
            (
                await session.execute(
                    user_dao.select_stmt(include_deleted=True).where(
                        User.deleted_at.is_not(None),
                        User.id == user.id,
                    )
                )
            )
            .scalars()
            .first()
        )
        active_by_filter = (
            (
                await session.execute(
                    user_dao.select_stmt(include_deleted=True).where(
                        User.deleted_at.is_(None),
                        User.id == user.id,
                    )
                )
            )
            .scalars()
            .first()
        )
        remaining_active = (
            (
                await session.execute(
                    user_dao.select_stmt(include_deleted=True).where(
                        User.deleted_at.is_(None),
                        User.id == active_user.id,
                    )
                )
            )
            .scalars()
            .first()
        )
        deleted_count = (
            await session.execute(
                user_dao.count_stmt(User.id, include_deleted=True).where(
                    User.deleted_at.is_not(None)
                )
            )
        ).scalar()
        active_count = (await session.execute(user_dao.count_stmt(User.id))).scalar()
        all_count = (
            await session.execute(user_dao.count_stmt(include_deleted=True))
        ).scalar()

    assert active is None
    assert deleted is not None
    assert deleted_by_filter is not None
    assert active_by_filter is None
    assert remaining_active is not None
    assert deleted_count == 1
    assert active_count == 1
    assert all_count == 2


@pytest.mark.asyncio
async def test_instance_update_logic(user_dao, db_session):
    user = User.create(username="old_name")
    await user_dao.insert(user)

    await user_dao.update(user, {User.username: "new_name"})

    reloaded = await user_dao.query_by_primary_id(user.id)
    assert reloaded.username == "new_name"


@pytest.mark.asyncio
async def test_failed_update_does_not_mutate_instance(user_dao, monkeypatch):
    user = User.create(username="before")
    await user_dao.insert(user)

    async def _fail_commit(*args, **kwargs):
        raise RuntimeError("database commit failed")

    monkeypatch.setattr(AsyncSession, "commit", _fail_commit)

    with pytest.raises(RuntimeError, match="database commit failed"):
        await user_dao.update(user, username="after")

    assert user.username == "before"
    assert user.updater_id is None
    assert user.updater_type is None


@pytest.mark.asyncio
async def test_explicit_transaction_executes_built_statement(user_dao):
    user = User.create(username="transaction_old")
    await user_dao.insert(user)

    statement = user_dao.update_stmt(
        User.id == user.id,
        values={"username": "transaction_new"},
    )
    async with user_dao.transaction() as session:
        await session.execute(statement)

    reloaded = await user_dao.query_by_primary_id(user.id)
    assert reloaded is not None
    assert reloaded.username == "transaction_new"


@pytest.mark.asyncio
async def test_explicit_audit_actor_works_without_request_context(
    user_dao,
    monkeypatch,
):
    def _missing_user_id():
        raise LookupError("user_id is not set")

    monkeypatch.setattr(database_base.context, "get_user_id", _missing_user_id)
    user = user_dao.create(
        audit_actor=AuditActor.task(1001),
        username="worker_created",
    )
    assert user.creator_id == 1001
    assert user.creator_type == AuditActorType.TASK.value
    await user_dao.insert(user)

    stored = await user_dao.query_by_primary_id(user.id)
    assert stored is not None
    await user_dao.update(
        stored,
        {User.username: "worker_updated"},
        audit_actor=AuditActor.service(1002),
    )

    reloaded = await user_dao.query_by_primary_id(user.id)
    assert reloaded is not None
    assert reloaded.updater_id == 1002
    assert reloaded.updater_type == AuditActorType.SERVICE.value

    await user_dao.update(
        reloaded,
        username="worker_updated_without_actor",
    )
    updated_without_actor = await user_dao.query_by_primary_id(user.id)
    assert updated_without_actor is not None
    assert updated_without_actor.updater_id is None
    assert updated_without_actor.updater_type == AuditActorType.SYSTEM.value


def test_missing_request_context_does_not_break_audit_defaults(monkeypatch):
    def _missing_user_id():
        raise LookupError("user_id is not set")

    monkeypatch.setattr(database_base.context, "get_user_id", _missing_user_id)
    user = User.create(username="worker_without_actor")

    assert user.creator_id is None
    assert user.creator_type == AuditActorType.SYSTEM.value
