"""Vector package public exports."""

from __future__ import annotations

from pkg.vectors.backends import (
    BackendProvider,
    BaseVectorBackend,
    CollectionSpec,
    IsolationMode,
    MetricType,
    MilvusBackend,
    ScalarDataType,
    ScalarFieldSpec,
    VectorBackend,
    create_backend,
)
from pkg.vectors.context_assembly import (
    AssembledContextChunk,
    AssembledContextWindow,
    AssembledDocumentContext,
    ContextAssemblyConfig,
    ContextAssemblyResult,
    ContextAssemblyStats,
    ContextBudgetConfig,
    ContextHeaderConfig,
    ContextWindowConfig,
    DocumentContextAssembler,
)
from pkg.vectors.contracts import (
    ConsistencyLevel,
    FilterCondition,
    FilterOperator,
    SearchHit,
    SearchRequest,
    VectorRecord,
)
from pkg.vectors.embedders import (
    EMBEDDER_BUILDERS,
    EmbedderProvider,
    OpenAICompatibleEmbedder,
    create_embedder,
    create_openai_compatible_embedder,
)
from pkg.vectors.errors import (
    CapabilityNotSupportedError,
    CollectionSchemaMismatchError,
    InvalidEmbeddingDimensionError,
    RecordValidationError,
    UnsupportedFilterError,
    VectorCoreError,
)
from pkg.vectors.post_retrieval import (
    CollapseConfig,
    CollapsedSearchHit,
    DedupConfig,
    DedupKeepStrategy,
    PostRetrievalConfig,
    PostRetrievalPipeline,
    PostRetrievalResult,
    PostRetrievalStats,
    ScoreAggregation,
)
from pkg.vectors.repositories import BaseVectorRepository, ScopeValue

__all__ = [
    "AssembledContextChunk",
    "AssembledContextWindow",
    "AssembledDocumentContext",
    "BackendProvider",
    "BaseVectorBackend",
    "BaseVectorRepository",
    "CapabilityNotSupportedError",
    "CollapseConfig",
    "CollapsedSearchHit",
    "CollectionSchemaMismatchError",
    "CollectionSpec",
    "ConsistencyLevel",
    "ContextAssemblyConfig",
    "ContextAssemblyResult",
    "ContextAssemblyStats",
    "ContextBudgetConfig",
    "ContextHeaderConfig",
    "ContextWindowConfig",
    "DedupConfig",
    "DedupKeepStrategy",
    "DocumentContextAssembler",
    "EMBEDDER_BUILDERS",
    "EmbedderProvider",
    "FilterCondition",
    "FilterOperator",
    "InvalidEmbeddingDimensionError",
    "IsolationMode",
    "MetricType",
    "MilvusBackend",
    "OpenAICompatibleEmbedder",
    "PostRetrievalConfig",
    "PostRetrievalPipeline",
    "PostRetrievalResult",
    "PostRetrievalStats",
    "RecordValidationError",
    "ScalarDataType",
    "ScalarFieldSpec",
    "ScopeValue",
    "ScoreAggregation",
    "SearchHit",
    "SearchRequest",
    "UnsupportedFilterError",
    "VectorBackend",
    "VectorCoreError",
    "VectorRecord",
    "create_backend",
    "create_embedder",
    "create_openai_compatible_embedder",
]
