CREATE TABLE IF NOT EXISTS `agent_audit` (
    `id` BIGINT NOT NULL COMMENT '主键 ID',
    `run_id` VARCHAR(64) NOT NULL COMMENT 'Agent 运行 ID',
    `agent_name` VARCHAR(64) NOT NULL COMMENT 'Agent 名称',
    `user_id` BIGINT NOT NULL COMMENT '用户 ID',
    `trace_id` VARCHAR(128) DEFAULT NULL COMMENT '请求 trace_id',
    `user_input` TEXT NOT NULL COMMENT '脱敏后的用户输入',
    `max_steps` INT NOT NULL COMMENT '最大执行步数',
    `status` VARCHAR(32) NOT NULL COMMENT '运行状态',
    `final_answer` TEXT DEFAULT NULL COMMENT '脱敏后的最终回答',
    `started_at` DATETIME NOT NULL COMMENT '运行开始时间 UTC',
    `ended_at` DATETIME DEFAULT NULL COMMENT '运行结束时间 UTC',
    `elapsed_ms` DOUBLE NOT NULL DEFAULT 0 COMMENT '运行耗时毫秒',
    `steps` JSON NOT NULL COMMENT '脱敏后的步骤记录',
    `llm_calls` JSON NOT NULL COMMENT '脱敏后的 LLM 调用记录',
    `metadata` JSON DEFAULT NULL COMMENT '审计扩展元数据',
    `creator_id` BIGINT NOT NULL COMMENT '创建人 ID',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater_id` BIGINT DEFAULT NULL COMMENT '更新人 ID',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted_at` DATETIME DEFAULT NULL COMMENT '删除时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_agent_audit_agent_run` (`agent_name`, `run_id`),
    INDEX `idx_agent_audit_user_created` (`user_id`, `created_at`),
    INDEX `idx_agent_audit_trace_id` (`trace_id`),
    INDEX `idx_agent_audit_agent_status` (`agent_name`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Agent 运行审计表';
