CREATE TABLE IF NOT EXISTS `agent_audit` (
    `id` BIGINT NOT NULL COMMENT '主键 ID',
    `run_id` VARCHAR(64) NOT NULL COMMENT 'Agent 运行 ID',
    `agent_name` VARCHAR(64) NOT NULL COMMENT 'Agent 名称',
    `user_id` BIGINT NOT NULL COMMENT '用户 ID',
    `trace_id` VARCHAR(128) DEFAULT NULL COMMENT '请求 trace_id',
    `user_input` TEXT NOT NULL COMMENT '脱敏后的用户输入',
    `max_steps` INT NOT NULL COMMENT '最大执行步数',
    `status` VARCHAR(32) NOT NULL COMMENT '运行状态',
    `final_answer` TEXT DEFAULT NULL COMMENT '脱敏后的最终回答',
    `started_at` DATETIME NOT NULL COMMENT '运行开始时间 UTC',
    `ended_at` DATETIME DEFAULT NULL COMMENT '运行结束时间 UTC',
    `elapsed_ms` DOUBLE NOT NULL DEFAULT 0 COMMENT '运行耗时毫秒',
    `steps` JSON NOT NULL COMMENT '脱敏后的步骤记录',
    `llm_calls` JSON NOT NULL COMMENT '脱敏后的 LLM 调用记录',
    `metadata` JSON DEFAULT NULL COMMENT '审计扩展元数据',
    `creator_id` BIGINT NOT NULL COMMENT '创建人 ID',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater_id` BIGINT DEFAULT NULL COMMENT '更新人 ID',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted_at` DATETIME DEFAULT NULL COMMENT '删除时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_agent_audit_agent_run` (`agent_name`, `run_id`),
    INDEX `idx_agent_audit_user_created` (`user_id`, `created_at`),
    INDEX `idx_agent_audit_trace_id` (`trace_id`),
    INDEX `idx_agent_audit_agent_status` (`agent_name`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Agent 运行审计表';

CREATE TABLE IF NOT EXISTS `agent_session` (
    `id` BIGINT NOT NULL COMMENT '主键 ID',
    `session_id` VARCHAR(64) NOT NULL COMMENT '对外会话 ID',
    `user_id` BIGINT NOT NULL COMMENT '用户 ID',
    `entrypoint` VARCHAR(32) NOT NULL COMMENT '创建会话的入口',
    `status` VARCHAR(32) NOT NULL COMMENT '会话状态',
    `title` VARCHAR(128) DEFAULT NULL COMMENT '会话标题',
    `rolling_summary` TEXT DEFAULT NULL COMMENT '滚动摘要',
    `working_state` JSON DEFAULT NULL COMMENT '工作状态',
    `recent_token_count` INT NOT NULL DEFAULT 0 COMMENT '最近上下文 token 数',
    `message_count` INT NOT NULL DEFAULT 0 COMMENT '消息数',
    `last_message_at` DATETIME DEFAULT NULL COMMENT '最后消息时间 UTC',
    `expires_at` DATETIME DEFAULT NULL COMMENT '过期时间 UTC',
    `creator_id` BIGINT NOT NULL COMMENT '创建人 ID',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater_id` BIGINT DEFAULT NULL COMMENT '更新人 ID',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted_at` DATETIME DEFAULT NULL COMMENT '删除时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_agent_session_session_id` (`session_id`),
    INDEX `idx_agent_session_user_status_updated` (`user_id`, `status`, `updated_at`),
    INDEX `idx_agent_session_user_last_message` (`user_id`, `last_message_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Agent 用户会话表';

CREATE TABLE IF NOT EXISTS `agent_message` (
    `id` BIGINT NOT NULL COMMENT '主键 ID',
    `message_id` VARCHAR(64) NOT NULL COMMENT '对外消息 ID',
    `session_id` VARCHAR(64) NOT NULL COMMENT '对外会话 ID',
    `run_id` VARCHAR(64) DEFAULT NULL COMMENT '关联运行 ID',
    `user_id` BIGINT NOT NULL COMMENT '用户 ID',
    `role` VARCHAR(16) NOT NULL COMMENT '消息角色',
    `content` TEXT NOT NULL COMMENT '消息内容',
    `content_summary` TEXT DEFAULT NULL COMMENT '消息摘要',
    `token_count` INT NOT NULL DEFAULT 0 COMMENT 'token 数',
    `metadata` JSON DEFAULT NULL COMMENT '消息元数据',
    `creator_id` BIGINT NOT NULL COMMENT '创建人 ID',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater_id` BIGINT DEFAULT NULL COMMENT '更新人 ID',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted_at` DATETIME DEFAULT NULL COMMENT '删除时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_agent_message_message_id` (`message_id`),
    INDEX `idx_agent_message_session_created` (`session_id`, `created_at`, `id`),
    INDEX `idx_agent_message_user_created` (`user_id`, `created_at`, `id`),
    INDEX `idx_agent_message_run_id` (`run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Agent 会话消息表';

CREATE TABLE IF NOT EXISTS `agent_run` (
    `id` BIGINT NOT NULL COMMENT '主键 ID',
    `run_id` VARCHAR(64) NOT NULL COMMENT '对外运行 ID',
    `session_id` VARCHAR(64) NOT NULL COMMENT '对外会话 ID',
    `user_id` BIGINT NOT NULL COMMENT '用户 ID',
    `entrypoint` VARCHAR(32) NOT NULL COMMENT '请求入口',
    `agent_name` VARCHAR(64) NOT NULL COMMENT 'Agent 名称',
    `route` VARCHAR(32) DEFAULT NULL COMMENT '路由结果',
    `status` VARCHAR(32) NOT NULL COMMENT '运行状态',
    `max_steps` INT NOT NULL COMMENT '最大执行步数',
    `trace_id` VARCHAR(128) DEFAULT NULL COMMENT '请求 trace_id',
    `started_at` DATETIME NOT NULL COMMENT '开始时间 UTC',
    `ended_at` DATETIME DEFAULT NULL COMMENT '结束时间 UTC',
    `elapsed_ms` DOUBLE NOT NULL DEFAULT 0 COMMENT '耗时毫秒',
    `error_code` VARCHAR(64) DEFAULT NULL COMMENT '错误码',
    `error_message` TEXT DEFAULT NULL COMMENT '错误信息',
    `metadata` JSON DEFAULT NULL COMMENT '运行元数据',
    `creator_id` BIGINT NOT NULL COMMENT '创建人 ID',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater_id` BIGINT DEFAULT NULL COMMENT '更新人 ID',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted_at` DATETIME DEFAULT NULL COMMENT '删除时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_agent_run_run_id` (`run_id`),
    INDEX `idx_agent_run_session_created` (`session_id`, `created_at`, `id`),
    INDEX `idx_agent_run_user_created` (`user_id`, `created_at`, `id`),
    INDEX `idx_agent_run_agent_status` (`agent_name`, `status`),
    INDEX `idx_agent_run_trace_id` (`trace_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Agent 单次运行表';

CREATE TABLE IF NOT EXISTS `agent_run_step` (
    `id` BIGINT NOT NULL COMMENT '主键 ID',
    `run_id` VARCHAR(64) NOT NULL COMMENT '对外运行 ID',
    `session_id` VARCHAR(64) NOT NULL COMMENT '对外会话 ID',
    `user_id` BIGINT NOT NULL COMMENT '用户 ID',
    `step_index` INT NOT NULL COMMENT '步骤序号',
    `status` VARCHAR(32) NOT NULL COMMENT '步骤状态',
    `action_type` VARCHAR(32) NOT NULL COMMENT '动作类型',
    `tool` VARCHAR(64) DEFAULT NULL COMMENT '工具名',
    `args` JSON DEFAULT NULL COMMENT '工具参数',
    `action_result` JSON DEFAULT NULL COMMENT '动作结果',
    `artifact_id` VARCHAR(64) DEFAULT NULL COMMENT '工具产物 ID',
    `error` TEXT DEFAULT NULL COMMENT '错误信息',
    `elapsed_ms` DOUBLE NOT NULL DEFAULT 0 COMMENT '步骤耗时毫秒',
    `creator_id` BIGINT NOT NULL COMMENT '创建人 ID',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater_id` BIGINT DEFAULT NULL COMMENT '更新人 ID',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted_at` DATETIME DEFAULT NULL COMMENT '删除时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_agent_run_step_run_index` (`run_id`, `step_index`),
    INDEX `idx_agent_run_step_session_created` (`session_id`, `created_at`, `id`),
    INDEX `idx_agent_run_step_user_created` (`user_id`, `created_at`, `id`),
    INDEX `idx_agent_run_step_tool` (`tool`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Agent 运行步骤表';

CREATE TABLE IF NOT EXISTS `scoped_operation_locks` (
    `id` BIGINT NOT NULL COMMENT '主键 ID',
    `operation_scope` VARCHAR(64) NOT NULL COMMENT '锁作用域',
    `resource_key` VARCHAR(128) NOT NULL COMMENT 'scope 内资源键',
    `creator_id` BIGINT DEFAULT NULL COMMENT '创建人 ID',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater_id` BIGINT DEFAULT NULL COMMENT '更新人 ID',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted_at` DATETIME DEFAULT NULL COMMENT '删除时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_scoped_op_lock_key` (`operation_scope`, `resource_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='通用事务互斥锁';
